name: RobbHenshaw
favicon: null
layout_spectrum: 0.09010150865651667
typography_spectrum: 0.16427913727238774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9365531478542835
  lightness: 0.5977212558500469
  saturation: 0.9429139653220773
  rhythmicContrast: 0.9184332294389606
purpose: []
